
title: My Resume
url: 'http://chatnaphaa.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Pai Chatnapha  ## put your name
title: 'GRAPHIC &amp; software developer'  ## your title
location: San Francisco , CA


## Social Profiles
facebook: https://www.facebook.com/cnp.orio  ## your facebook account url
twitter: https://twitter.com/cnp_orio?lang=th  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
